openapi: 3.0.0
info:
  version: 1.0.0
  title: Heroku Agents API
  description: Intelligent agents for billing operations and system monitoring, accessible via Slack and Salesforce AppLink.
servers:
  - url: /
x-sfdc:
  agent:
    topic:
      classificationDescription: This topic provides access to intelligent billing and operations agents that can analyze costs, monitor system health, investigate incidents, and provide operational insights using AWS tools and Better Stack monitoring.
      scope: Your job is to help users understand billing information, analyze costs, monitor system health, troubleshoot issues, and investigate security and compliance matters. You have access to billing agents for AWS cost analysis and CloudTrail auditing, and operations agents for system monitoring and incident management.
      instructions:
        - Use the billing agent to answer questions about AWS costs, usage patterns, security audits, and compliance.
        - Use the operations agent to check system status, investigate incidents, analyze logs, and monitor infrastructure.
        - Both agents have access to specialized tools including AWS CloudTrail, AWS Well-Architected Security Assessment, and Better Stack monitoring.
        - Provide accurate, actionable insights based on real-time data from these systems.
        - NEVER make up data - always use the agent tools to retrieve accurate information.
      name: heroku_agents
paths:
  /:
    get:
      tags:
        - general
      summary: Welcome endpoint
      operationId: ReadRoot
      description: A welcoming root endpoint that provides information about the API
      responses:
        '200':
          description: Successfully returned welcome message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Welcome to the Agents!
                  docs_url:
                    type: string
                    example: /docs
                  api_prefix:
                    type: string
                    example: /api
  /health:
    get:
      tags:
        - general
      summary: Health check endpoint
      operationId: GetHealth
      description: Check if the application is running and healthy
      responses:
        '200':
          description: Application is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
  /billing/query:
    post:
      tags:
        - billing
      summary: Query the billing agent
      operationId: QueryBillingAgent
      x-sfdc:
        heroku:
          authorization:
            connectedApp: 'HerokuAgents'
            permissionSet: 'HerokuAgentsPermSet'
        agent:
          action:
            publishAsAgentAction: true
            isUserInput: true
            isDisplayable: true
      description: |
        Submit a billing-related query to the intelligent billing agent.
        
        The billing agent specializes in:
        - Monitoring billing and usage metrics
        - Analyzing cost trends and usage patterns
        - Providing billing insights and cost optimization recommendations
        - Managing billing alerts and thresholds
        - Tracking AWS CloudTrail events for billing-related API calls and audit logs
        - Investigating security and compliance issues related to billing
        - Monitoring security service costs and optimizing security spending
        - Assessing security posture for cost-effective compliance
        
        The agent has access to AWS CloudTrail, AWS Well-Architected Security Assessment,
        and AWS Documentation tools to provide accurate, actionable information.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: Successfully processed query
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /billing/health:
    get:
      tags:
        - billing
      summary: Billing agent health check
      operationId: BillingHealthCheck
      description: Check if the billing agent is initialized and ready to process queries
      responses:
        '200':
          description: Agent is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
  /ops/query:
    post:
      tags:
        - ops
      summary: Query the operations agent
      operationId: QueryOpsAgent
      x-sfdc:
        heroku:
          authorization:
            connectedApp: 'HerokuAgents'
            permissionSet: 'HerokuAgentsPermSet'
        agent:
          action:
            publishAsAgentAction: true
            isUserInput: true
            isDisplayable: true
      description: |
        Submit an operations-related query to the intelligent operations agent.
        
        The operations agent specializes in:
        - Monitoring system health and performance
        - Analyzing logs and metrics
        - Troubleshooting issues and outages
        - Providing operational insights and recommendations
        - Managing infrastructure and deployments
        - Responding to alerts and incidents
        
        The agent has access to Better Stack monitoring tools and other MCP servers
        to provide accurate, actionable information about system operations.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
      responses:
        '200':
          description: Successfully processed query
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /ops/health:
    get:
      tags:
        - ops
      summary: Operations agent health check
      operationId: OpsHealthCheck
      description: Check if the ops agent is initialized and ready to process queries
      responses:
        '200':
          description: Agent is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
components:
  schemas:
    QueryRequest:
      type: object
      required:
        - query
      properties:
        query:
          type: string
          minLength: 1
          maxLength: 10000
          description: The query to process (billing-related or operations-related depending on the endpoint)
          example: What are my current AWS costs?
    QueryResponse:
      type: object
      properties:
        query:
          type: string
          description: The original query that was processed
          example: What are my current AWS costs?
        response:
          type: string
          description: The agent's response to the query
          example: Based on CloudTrail data, your current AWS costs are approximately $150/month. The main cost drivers are EC2 instances ($80/month) and S3 storage ($40/month). Consider using Reserved Instances to reduce EC2 costs by up to 30%.
        agent:
          type: string
          description: The name of the agent that processed the query
          example: Strands Billing Agent
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message
          example: Invalid request
        detail:
          type: string
          nullable: true
          description: Additional error details
          example: Query field is required
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          description: Health status of the agent
          example: healthy
        agent:
          type: string
          description: Name of the agent
          example: Strands Billing Agent
        temperature:
          type: number
          description: Temperature setting for the agent (affects response consistency)
          example: 0.2
